version: "3"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "instawork-assignment"
      MYSQL_USER: "instawork"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - ./compose.env
    depends_on:
      - db
